import { jsPDF } from "jspdf";
import { useEffect, useState } from "react";
import { NavigatorLayout } from "@/components/navigator/NavigatorLayout";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const disclaimer = "DRAFT DOCUMENT — Generated by UAIU Navigator for preparation purposes only. This document has not been reviewed or approved by Verra or any accredited VVB. Do not submit this document directly to Verra without professional review.";

export default function NavigatorGenerate({ params }: any) {
  const id = params.id;
  const [project, setProject] = useState<any>(null);
  const [status, setStatus] = useState('');
  useEffect(() => { fetch(`/api/navigator/projects/${id}`, { headers: { Authorization: `Bearer ${localStorage.getItem('session_id') || ''}` } }).then(r=>r.json()).then(d=>setProject(d.project)); }, [id]);
  const buildPdf = (title: string, lines: string[]) => {
    const doc = new jsPDF();
    doc.setFillColor(21,128,61); doc.rect(0,0,210,12,'F');
    doc.setFontSize(12); doc.text('UAIU Navigator', 14, 8, { baseline: 'middle' });
    doc.setFontSize(16); doc.text(title, 14, 24);
    let y = 34; lines.forEach(line => { doc.setFontSize(11); doc.text(line, 14, y); y += 7; });
    doc.setFontSize(9); doc.text('Generated by UAIU Navigator · uaiu.live/x/navigator', 14, 286);
    doc.text('DRAFT — For Preparation Purposes Only. Not a Verra Official Document.', 14, 292);
    doc.text(disclaimer, 14, 270, { maxWidth: 182 });
    return doc;
  };
  const generateAll = async () => {
    if (!project) return;
    const docs = [
      { name: 'project-description-summary.pdf', doc: buildPdf('Project Description Summary', [`Project Title: ${project.project_name}`, `Project Type: ${project.project_type}`, `Methodology: ${project.methodology_selected}`, `Estimated GHG Reductions: ${project.estimated_tonnes || 'TBD'} tonnes/year`]) },
      { name: 'vvb-engagement-letter.pdf', doc: buildPdf('VVB Engagement Letter', [`To: Validation and Verification Body`, `Re: ${project.project_name}`, `We request validation and verification services for this project.`]) },
      { name: 'registration-readiness-report.pdf', doc: buildPdf('Registration Readiness Report', [`Readiness score: ${project.readiness_score || 0}`, `Status: ${project.registration_status}`, `Next step: Engage a VVB`]) },
    ];
    docs.forEach(f => f.doc.save(f.name));
    try {
      await fetch(`/api/navigator/projects/${id}/email-docs`, { method: 'POST', headers: { 'Content-Type':'application/json', Authorization: `Bearer ${localStorage.getItem('session_id') || ''}` }, body: JSON.stringify({ to: project.email, projectName: project.project_name, readinessScore: project.readiness_score || 0, files: docs.map(d => ({ name: d.name, base64: d.doc.output('datauristring').split(',')[1] })) }) });
      setStatus('Documents emailed successfully.');
    } catch { setStatus('Email delivery failed. Use Resend Email.'); }
  };

  return <NavigatorLayout><Card className="p-6"><h1 className="text-xl font-semibold">Document Generator</h1><p className="mt-2 text-sm text-[#475569]">Generate the 3 required draft PDFs and email them to your registered address.</p><Button className="mt-4 h-11 bg-[#15803D]" onClick={generateAll}>Generate and Email PDFs</Button>{status && <p className="mt-3 text-sm">{status}</p>}</Card></NavigatorLayout>;
}
